version: '3.8'

services:
  mongodb1:
    image: mongo:latest
    container_name: mongodb1
    ports:
      - "27017:27017"
    volumes:
      - mongodb1_data:/data/db
    networks:
      - app_network

  python_app:
    build:
      context: ./
    container_name: python_app
    ports:
      - "5000:5000"
    depends_on:
      - mongodb1
    volumes:
      - ./:/app 

    networks:
      - app_network

volumes:
  mongodb1_data:

networks:
  app_network:
    driver: bridge